- hosts: leaf1-DC1
  gather_facts: no
  vars:
    vlans1:
      - 4000
      - 4001
      - 4002
  tasks:
    - name: Add VLANs via looping
      eos_vlans:
        config:
          - vlan_id:  "{{ item }}"
            state: active
      loop: "{{ vlans1 }}"


